swagger: "2.0"
info:
  description: "scala-mlサーバのAPIです。"
  version: "1.0.0"
  title: "scala-ml-server API"
paths:
  /execution_result/{result_id}:
    get:
      summary: "実行結果情報API"
      description: "指定されたresult_idの実行結果の情報を返します"
      parameters:
      - name: "result_id"
        in: "path"
        description: "取得したい実行結果のID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "light-gbm.py"
